/*
  This file is automatically generated using the npm run generate_ts_types_from_go command.
  Its purpose is to keeep the typings between Go and TS in sync
*/

export type DepositSlip = {
  BankNumber: string;
  Amount: string;
  Municipality: string;
  RevenueType: string;
  PaymentType: string;
  DateFrom: string;
  DateTo: string;
  BudgetNumber: string;
  CallNumber: string;
  Reason: string;
};

export type DepositSlipOutput = {
  PioMio: DepositSlip;
  ZdravstvoKanton: DepositSlip;
  ZdravstvoFbih: DepositSlip;
  NezaposlenostKanton: DepositSlip;
  NezaposlenostFbih: DepositSlip;
};
